version: 0.2

phases:
  install:
    commands:
      - echo Nothing to install for static site
  build:
    commands:
      - echo No build step required for HTML site
  post_build:
    commands:
      - echo Uploading to S3...
      - aws s3 sync . s3://my-static-bucket/ --delete

artifacts:
  files:
    - '**/*'
